{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "87702fef",
   "metadata": {
    "papermill": {
     "duration": 0.003232,
     "end_time": "2026-02-12T18:26:39.588336",
     "exception": false,
     "start_time": "2026-02-12T18:26:39.585104",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6c5a0af2",
   "metadata": {
    "_cell_guid": "ff8def23-8633-498d-a802-ccf2413877a2",
    "_uuid": "3ce6971a-636e-4036-b6fe-9f6e7f021caf",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-02-12T18:26:39.596672Z",
     "iopub.status.busy": "2026-02-12T18:26:39.596247Z",
     "iopub.status.idle": "2026-02-12T18:27:06.622321Z",
     "shell.execute_reply": "2026-02-12T18:27:06.621146Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 27.034496,
     "end_time": "2026-02-12T18:27:06.625235",
     "exception": false,
     "start_time": "2026-02-12T18:26:39.590739",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-12 18:26:41.726703: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1770920801.954741      17 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1770920802.023413      17 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "W0000 00:00:1770920802.601074      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1770920802.601122      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1770920802.601126      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
      "W0000 00:00:1770920802.601129      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================================\n",
      "⚛️  QuoreMind v1.0.0: Sistema Metripléctico Cuántico-Bayesiano\n",
      "================================================================================\n",
      "\n",
      "📊 1. ANÁLISIS CON ESTRUCTURA METRIPLÉCTICA (Ciclo 1)\n",
      "--------------------------------------------------------------------------------\n",
      "⏱️  calculate_probabilities_and_select_action ejecutado en 0.0001s\n",
      "⏱️  simulate_wave_collapse_metriplectic ejecutado en 0.0750s\n",
      "✓ Estado colapsado: -6.303107\n",
      "✓ Acción tomada: 1\n",
      "✓ Entropía Shannon (norm): 0.958376\n",
      "✓ Entropía von Neumann: 0.500000\n",
      "✓ Coherencia: 0.263814\n",
      "✓ Mahalanobis (norm): 0.777634\n",
      "✓ Evolución metripléctica: -0.100000\n",
      "✓ Posterior bayesiana: 0.810000\n",
      "✓ Cosenos (x, y, z): (0.6033, 0.4896, 0.6295)\n",
      "\n",
      "🔄 2. ANÁLISIS DE CORCHETES DE POISSON\n",
      "--------------------------------------------------------------------------------\n",
      "✓ {x, H}: 0.263814 (esperado: p ≈ 0.263814)\n",
      "✓ {p, H}: -0.958376 (esperado: -q ≈ -0.958376)\n",
      "✓ dx/dt = {x, H}: 0.263814\n",
      "\n",
      "⚙️  3. ESTRUCTURA METRIPLÉCTICA DETALLADA\n",
      "--------------------------------------------------------------------------------\n",
      "✓ [H, S]_M (metriplexico): -0.100000\n",
      "✓ dH/dt (reversible+disipativa): -0.100000\n",
      "✓ dS/dt (producción de entropía): 0.101206\n",
      "\n",
      "📈 4. OPTIMIZACIÓN DE ESTADOS CUÁNTICOS\n",
      "--------------------------------------------------------------------------------\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0263s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0038s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0038s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-12 18:27:05.712984: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "⏱️  objective_function_with_noise ejecutado en 0.0064s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0039s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0040s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0042s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0038s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0043s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0039s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0037s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0042s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0038s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0037s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0040s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0038s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0033s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0045s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0038s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0039s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0040s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0036s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0034s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0040s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0037s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0035s\n",
      "⏱️  optimize_quantum_state ejecutado en 0.8353s\n",
      "⏱️  objective_function_with_noise ejecutado en 0.0029s\n",
      "✓ Objetivo inicial: 4.227154\n",
      "✓ Objetivo final: -5.009411\n",
      "✓ Mejora: 9.236565\n",
      "\n",
      "🔁 5. EVOLUCIÓN TEMPORAL DEL SISTEMA\n",
      "--------------------------------------------------------------------------------\n",
      "Simulando 5 ciclos de colapso:\n",
      "⏱️  calculate_probabilities_and_select_action ejecutado en 0.0001s\n",
      "⏱️  simulate_wave_collapse_metriplectic ejecutado en 0.0028s\n",
      "\n",
      "  Ciclo 1:\n",
      "    - von Neumann entropy: 0.5000\n",
      "    - Shannon (norm): 0.9584\n",
      "    - Mahalanobis (norm): 0.7776\n",
      "    - Evolución metripléctica: -0.1000\n",
      "    - Acción: 1\n",
      "⏱️  calculate_probabilities_and_select_action ejecutado en 0.0000s\n",
      "⏱️  simulate_wave_collapse_metriplectic ejecutado en 0.0025s\n",
      "\n",
      "  Ciclo 2:\n",
      "    - von Neumann entropy: 0.5000\n",
      "    - Shannon (norm): 0.9583\n",
      "    - Mahalanobis (norm): 0.7776\n",
      "    - Evolución metripléctica: -0.1000\n",
      "    - Acción: 1\n",
      "⏱️  calculate_probabilities_and_select_action ejecutado en 0.0000s\n",
      "⏱️  simulate_wave_collapse_metriplectic ejecutado en 0.0024s\n",
      "\n",
      "  Ciclo 3:\n",
      "    - von Neumann entropy: 0.5000\n",
      "    - Shannon (norm): 0.9583\n",
      "    - Mahalanobis (norm): 0.7777\n",
      "    - Evolución metripléctica: -0.1000\n",
      "    - Acción: 1\n",
      "⏱️  calculate_probabilities_and_select_action ejecutado en 0.0000s\n",
      "⏱️  simulate_wave_collapse_metriplectic ejecutado en 0.0025s\n",
      "\n",
      "  Ciclo 4:\n",
      "    - von Neumann entropy: 0.5000\n",
      "    - Shannon (norm): 0.9583\n",
      "    - Mahalanobis (norm): 0.7774\n",
      "    - Evolución metripléctica: -0.1000\n",
      "    - Acción: 1\n",
      "⏱️  calculate_probabilities_and_select_action ejecutado en 0.0001s\n",
      "⏱️  simulate_wave_collapse_metriplectic ejecutado en 0.0025s\n",
      "\n",
      "  Ciclo 5:\n",
      "    - von Neumann entropy: 0.5000\n",
      "    - Shannon (norm): 0.9584\n",
      "    - Mahalanobis (norm): 0.7776\n",
      "    - Evolución metripléctica: -0.1000\n",
      "    - Acción: 1\n",
      "\n",
      "================================================================================\n",
      "🔷 6. ANÁLISIS CON OPERADOR ÁUREO Y PARÁMETRO λ_DOBLE\n",
      "================================================================================\n",
      "\n",
      "📌 Estados iniciales indexados:\n",
      "[[0.  0.1]\n",
      " [0.1 0.2]\n",
      " [0.2 0.3]\n",
      " [0.3 0.4]\n",
      " [0.4 0.5]\n",
      " [0.5 0.6]\n",
      " [0.6 0.7]\n",
      " [0.7 0.8]\n",
      " [0.8 0.9]\n",
      " [0.9 1. ]]\n",
      "\n",
      "📊 Qubits: [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]\n",
      "\n",
      "🟢 Parámetro λ_doble (Estados Legítimos):\n",
      "   Estado 0: λ_doble = 0.000247\n",
      "   Estado 1: λ_doble = 0.004268\n",
      "   Estado 2: λ_doble = 0.017718\n",
      "   ... (10 total)\n",
      "\n",
      "   Media: 0.250330\n",
      "   Desv. Est.: 0.278039\n",
      "\n",
      "🔴 Generando Estados Anómalos:\n",
      "   Estado 0: λ_doble = -23.801949\n",
      "   Estado 1: λ_doble = 4.335925\n",
      "   Estado 2: λ_doble = 148.903350\n",
      "   Estado 3: λ_doble = -1.257517\n",
      "   Estado 4: λ_doble = 14.883289\n",
      "\n",
      "⚠️  Umbral de detección (3σ): 1.084446\n",
      "\n",
      "✓ Anomalías detectadas: 3/5\n",
      "\n",
      "================================================================================\n",
      "📊 RESUMEN FINAL\n",
      "================================================================================\n",
      "\n",
      "✓ Operador Áureo (φ-operator):\n",
      "  - 10 estados indexados procesados\n",
      "  - Modulación de fase cuasiperiódica integrada\n",
      "  - Estabilización de optimización: ACTIVA\n",
      "\n",
      "✓ Parámetro λ_doble (λ₂):\n",
      "  - Detecta anomalías mediante:\n",
      "    * Amplitud máxima de estado\n",
      "    * Operador áureo (φ)\n",
      "    * Efectos Hamiltonianos\n",
      "    * Media de qubits\n",
      "  - Umbral de detección: 1.084446\n",
      "  - Sensibilidad: 60.0%\n",
      "\n",
      "✓ Estructura Metripléctica:\n",
      "  - Parte reversible (Poisson): 0.263814\n",
      "  - Parte disipativa (Métrica): -0.100000\n",
      "  - Producción de entropía: 0.101206\n",
      "\n",
      "✓ Lógica Bayesiana:\n",
      "  - Posterior: 0.810000\n",
      "  - Coherencia: 0.263814\n",
      "  - Acción: ACEPTAR\n",
      "\n",
      "✓ Optimización:\n",
      "  - Mejora de pérdida: 9.236565\n",
      "  - Iteraciones: 50\n",
      "  - Convergencia: ✓ EXITOSA\n",
      "    \n",
      "================================================================================\n",
      "✅ QuoreMind v1.0.0 - Análisis Completo\n",
      "================================================================================\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import tensorflow_probability as tfp\n",
    "from typing import Tuple, List, Dict, Union, Any, Optional, Callable\n",
    "from scipy.spatial.distance import mahalanobis\n",
    "from sklearn.covariance import EmpiricalCovariance\n",
    "import functools\n",
    "import time\n",
    "from dataclasses import dataclass\n",
    "\n",
    "# ============================================================================\n",
    "# DECORADORES Y UTILIDADES\n",
    "# ============================================================================\n",
    "\n",
    "def timer_decorator(func: Callable) -> Callable:\n",
    "    \"\"\"Decorador que mide el tiempo de ejecución.\"\"\"\n",
    "    @functools.wraps(func)\n",
    "    def wrapper(*args, **kwargs):\n",
    "        start_time = time.time()\n",
    "        result = func(*args, **kwargs)\n",
    "        end_time = time.time()\n",
    "        print(f\"⏱️  {func.__name__} ejecutado en {end_time - start_time:.4f}s\")\n",
    "        return result\n",
    "    return wrapper\n",
    "\n",
    "\n",
    "def validate_input_decorator(min_val: float = 0.0, max_val: float = 1.0) -> Callable:\n",
    "    \"\"\"Decorador que valida argumentos numéricos en un rango.\"\"\"\n",
    "    def decorator(func: Callable) -> Callable:\n",
    "        @functools.wraps(func)\n",
    "        def wrapper(*args, **kwargs):\n",
    "            for i, arg in enumerate(args[1:], 1):\n",
    "                if isinstance(arg, (int, float)) and not (min_val <= arg <= max_val):\n",
    "                    raise ValueError(f\"Argumento {i} debe estar entre {min_val} y {max_val}. Valor: {arg}\")\n",
    "            for name, arg in kwargs.items():\n",
    "                if isinstance(arg, (int, float)) and not (min_val <= arg <= max_val):\n",
    "                    raise ValueError(f\"Argumento {name} debe estar entre {min_val} y {max_val}. Valor: {arg}\")\n",
    "            return func(*args, **kwargs)\n",
    "        return wrapper\n",
    "    return decorator\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# OPERADOR ÁUREO Y PARÁMETROS\n",
    "# ============================================================================\n",
    "\n",
    "def golden_ratio_operator(dimension: int, index: int = 0) -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Calcula el Operador Áureo (φ-operator) para modular fase cuasiperiódica.\n",
    "    φ = (1 + √5) / 2 ≈ 1.618\n",
    "    \"\"\"\n",
    "    phi = (1.0 + np.sqrt(5.0)) / 2.0\n",
    "    phases = np.array([phi**(i + index) % (2 * np.pi) for i in range(dimension)])\n",
    "    operator = np.exp(1j * phases)\n",
    "    return operator / np.linalg.norm(operator)\n",
    "\n",
    "\n",
    "def aureo_operator(n: int, phi: float = 1.6180339887) -> Tuple[float, float]:\n",
    "    \"\"\"Calcula paridad y fase del operador áureo Ô_n.\"\"\"\n",
    "    n_float = float(n)\n",
    "    paridad = np.cos(np.pi * n_float)\n",
    "    fase_mod = np.cos(np.pi * phi * n_float)\n",
    "    return paridad, fase_mod\n",
    "\n",
    "\n",
    "def lambda_doble_operator(state_vector: np.ndarray,\n",
    "                         hamiltonian: Callable,\n",
    "                         qubits: np.ndarray,\n",
    "                         golden_phase: int = 0) -> float:\n",
    "    \"\"\"\n",
    "    Parámetro λ_doble: combina amplitud + operador áureo + qubits para detectar anomalías.\n",
    "    λ_doble = (weighted_sum * aureo_component * hamiltonian_effects) / mean_qbits\n",
    "    \"\"\"\n",
    "    amplitude = np.max(np.abs(state_vector))\n",
    "    weighted_sum = np.sum(state_vector * amplitude)\n",
    "    mean_qbits = np.mean(qubits)\n",
    "    mean_qbits = max(mean_qbits, 1e-6)\n",
    "\n",
    "    aureo_op = golden_ratio_operator(len(state_vector), golden_phase)\n",
    "    aureo_component = np.abs(np.dot(aureo_op, state_vector))\n",
    "\n",
    "    hamiltonian_effects = np.mean([hamiltonian(q, 0.0) for q in qubits])\n",
    "\n",
    "    lambda_doble = (weighted_sum * aureo_component * hamiltonian_effects) / mean_qbits\n",
    "    return float(np.real(lambda_doble))\n",
    "\n",
    "\n",
    "def calculate_cosines(entropy: float, prn_object: float) -> Tuple[float, float, float]:\n",
    "    \"\"\"Calcula los cosenos directores (x, y, z) para un vector 3D.\"\"\"\n",
    "    epsilon = 1e-6\n",
    "    entropy = max(entropy, epsilon)\n",
    "    prn_object = max(prn_object, epsilon)\n",
    "    magnitude = np.sqrt(entropy ** 2 + prn_object ** 2 + 1)\n",
    "    cos_x = entropy / magnitude\n",
    "    cos_y = prn_object / magnitude\n",
    "    cos_z = 1 / magnitude\n",
    "    return cos_x, cos_y, cos_z\n",
    "\n",
    "\n",
    "# Definir observables globales\n",
    "H = lambda q, p: 0.5 * p**2 + 0.5 * q**2\n",
    "S = lambda q, p: -0.5 * np.log(q**2 + p**2 + 1e-6)\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# ENTROPÍA VON NEUMANN\n",
    "# ============================================================================\n",
    "\n",
    "class VonNeumannEntropy:\n",
    "    \"\"\"Entropía de von Neumann para operadores de densidad cuánticos.\"\"\"\n",
    "\n",
    "    @staticmethod\n",
    "    def compute_von_neumann_entropy(density_matrix: np.ndarray,\n",
    "                                   epsilon: float = 1e-15,\n",
    "                                   normalize: bool = True,\n",
    "                                   method: str = \"sigmoid\") -> float:\n",
    "        \"\"\"\n",
    "        Calcula S = -Tr(ρ log ρ) donde ρ es la matriz de densidad.\n",
    "        \"\"\"\n",
    "        eigenvalues = np.linalg.eigvalsh(density_matrix)\n",
    "        eigenvalues = np.clip(eigenvalues, epsilon, None)\n",
    "        entropy = -np.sum(eigenvalues * np.log2(eigenvalues))\n",
    "\n",
    "        if not normalize:\n",
    "            return float(entropy)\n",
    "\n",
    "        dim = len(eigenvalues)\n",
    "        max_entropy = np.log2(dim)\n",
    "\n",
    "        if method == \"sigmoid\":\n",
    "            normalized = 1.0 / (1.0 + np.exp(-entropy))\n",
    "        elif method == \"tanh\":\n",
    "            normalized = (np.tanh(entropy / 2.0) + 1.0) / 2.0\n",
    "        elif method == \"log_compression\":\n",
    "            normalized = np.log(1.0 + entropy) / np.log(1.0 + max_entropy)\n",
    "        elif method == \"min_max\":\n",
    "            normalized = entropy / max_entropy\n",
    "        elif method == \"clamp\":\n",
    "            normalized = np.clip(entropy / max_entropy, 0.0, 1.0)\n",
    "        else:\n",
    "            raise ValueError(f\"Método desconocido: {method}\")\n",
    "\n",
    "        return float(np.clip(normalized, 0.0, 1.0))\n",
    "\n",
    "    @staticmethod\n",
    "    def density_matrix_from_state(state: np.ndarray) -> np.ndarray:\n",
    "        \"\"\"Construye ρ = |ψ⟩⟨ψ| desde un estado puro.\"\"\"\n",
    "        return np.outer(state, np.conj(state))\n",
    "\n",
    "    @staticmethod\n",
    "    def mixed_state_entropy(probabilities: List[float],\n",
    "                           density_matrices: List[np.ndarray]) -> float:\n",
    "        \"\"\"Entropía para mezcla: ρ = Σᵢ pᵢ ρᵢ\"\"\"\n",
    "        rho_mixed = np.zeros_like(density_matrices[0], dtype=complex)\n",
    "        for p, rho in zip(probabilities, density_matrices):\n",
    "            rho_mixed += p * rho\n",
    "        return VonNeumannEntropy.compute_von_neumann_entropy(rho_mixed)\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# ESTRUCTURA SIMPLÉCTICA\n",
    "# ============================================================================\n",
    "\n",
    "class PoissonBrackets:\n",
    "    \"\"\"Estructura simpléctica con corchetes de Poisson {f, g}.\"\"\"\n",
    "\n",
    "    @staticmethod\n",
    "    def _to_scalar(val: Union[np.ndarray, float]) -> float:\n",
    "        \"\"\"Convierte un array de un solo elemento (0-D o 1-D) a un escalar float.\"\"\"\n",
    "        if isinstance(val, np.ndarray):\n",
    "            return val.item()\n",
    "        return float(val)\n",
    "\n",
    "    @staticmethod\n",
    "    def poisson_bracket(f: Callable, g: Callable,\n",
    "                       q: np.ndarray, p: np.ndarray,\n",
    "                       eps: float = 1e-5) -> float:\n",
    "        \"\"\"Calcula {f, g} = (∂f/∂q)(∂g/∂p) - (∂f/∂p)(∂g/∂q)\"\"\"\n",
    "        # Ensure q and p are arrays, even if single-element\n",
    "        q = np.atleast_1d(q)\n",
    "        p = np.atleast_1d(p)\n",
    "\n",
    "        df_dq_val = (f(q + eps, p) - f(q - eps, p)) / (2 * eps)\n",
    "        df_dp_val = (f(q, p + eps) - f(q, p - eps)) / (2 * eps)\n",
    "        dg_dq_val = (g(q + eps, p) - g(q - eps, p)) / (2 * eps)\n",
    "        dg_dp_val = (g(q, p + eps) - g(q, p - eps)) / (2 * eps)\n",
    "\n",
    "        df_dq = PoissonBrackets._to_scalar(df_dq_val)\n",
    "        df_dp = PoissonBrackets._to_scalar(df_dp_val)\n",
    "        dg_dq = PoissonBrackets._to_scalar(dg_dq_val)\n",
    "        dg_dp = PoissonBrackets._to_scalar(dg_dp_val)\n",
    "\n",
    "        return float(df_dq * dg_dp - df_dp * dg_dq)\n",
    "\n",
    "    @staticmethod\n",
    "    def liouville_evolution(H: Callable, f: Callable,\n",
    "                           q: np.ndarray, p: np.ndarray) -> float:\n",
    "        \"\"\"Ecuación de Liouville: df/dt = {f, H}\"\"\"\n",
    "        return PoissonBrackets.poisson_bracket(f, H, q, p)\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# ESTRUCTURA METRIPLÉCTICA\n",
    "# ============================================================================\n",
    "\n",
    "class MetriplecticStructure:\n",
    "    \"\"\"Estructura metripléctica: parte simpléctica + parte métrica (disipativa).\"\"\"\n",
    "\n",
    "    @staticmethod\n",
    "    def metriplectic_bracket(f: Callable, g: Callable,\n",
    "                            q: np.ndarray, p: np.ndarray,\n",
    "                            M: np.ndarray,\n",
    "                            eps: float = 1e-5) -> float:\n",
    "        \"\"\"Corchete metriplexico: [f, g] = {f, g} + [f, g]_M\"\"\"\n",
    "        # Ensure q and p are arrays, even if single-element\n",
    "        q = np.atleast_1d(q)\n",
    "        p = np.atleast_1d(p)\n",
    "\n",
    "        poisson_part = PoissonBrackets.poisson_bracket(f, g, q, p, eps)\n",
    "\n",
    "        df_dq_val = (f(q + eps, p) - f(q - eps, p)) / (2 * eps)\n",
    "        df_dp_val = (f(q, p + eps) - f(q, p - eps)) / (2 * eps)\n",
    "        grad_f_q = PoissonBrackets._to_scalar(df_dq_val)\n",
    "        grad_f_p = PoissonBrackets._to_scalar(df_dp_val)\n",
    "        grad_f = np.array([grad_f_q, grad_f_p])\n",
    "\n",
    "        dg_dq_val = (g(q + eps, p) - g(q - eps, p)) / (2 * eps)\n",
    "        dg_dp_val = (g(q, p + eps) - g(q, p - eps)) / (2 * eps)\n",
    "        grad_g_q = PoissonBrackets._to_scalar(dg_dq_val)\n",
    "        grad_g_p = PoissonBrackets._to_scalar(dg_dp_val)\n",
    "        grad_g = np.array([grad_g_q, grad_g_p])\n",
    "\n",
    "        metric_part = np.dot(grad_f, np.dot(M, grad_g))\n",
    "        return float(poisson_part + metric_part)\n",
    "\n",
    "    @staticmethod\n",
    "    def metriplectic_evolution(H: Callable, S: Callable, f: Callable,\n",
    "                              q: np.ndarray, p: np.ndarray,\n",
    "                              M: np.ndarray,\n",
    "                              eps: float = 1e-5) -> float:\n",
    "        \"\"\"Ecuación metripléctica: df/dt = {f, H} + [f, S]_M\"\"\"\n",
    "        hamiltonian_part = PoissonBrackets.poisson_bracket(f, H, q, p, eps)\n",
    "        dissipative_part = MetriplecticStructure.metriplectic_bracket(f, S, q, p, M, eps)\n",
    "        return float(hamiltonian_part + dissipative_part)\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# CONFIGURACIÓN Y LÓGICA BAYESIANA\n",
    "# ============================================================================\n",
    "\n",
    "@dataclass\n",
    "class BayesLogicConfig:\n",
    "    \"\"\"Configuración para BayesLogic.\"\"\"\n",
    "    epsilon: float = 1e-6\n",
    "    high_entropy_threshold: float = 0.8\n",
    "    high_coherence_threshold: float = 0.6\n",
    "    action_threshold: float = 0.5\n",
    "\n",
    "\n",
    "class BayesLogic:\n",
    "    \"\"\"Lógica bayesiana para cálculo de probabilidades.\"\"\"\n",
    "\n",
    "    def __init__(self, config: Optional[BayesLogicConfig] = None):\n",
    "        self.config = config or BayesLogicConfig()\n",
    "\n",
    "    @validate_input_decorator(0.0, 1.0)\n",
    "    def calculate_posterior_probability(self, prior_a: float, prior_b: float,\n",
    "                                       conditional_b_given_a: float) -> float:\n",
    "        \"\"\"P(A|B) = (P(B|A) * P(A)) / P(B)\"\"\"\n",
    "        prior_b = max(prior_b, self.config.epsilon)\n",
    "        return (conditional_b_given_a * prior_a) / prior_b\n",
    "\n",
    "    @validate_input_decorator(0.0, 1.0)\n",
    "    def calculate_conditional_probability(self, joint_probability: float, prior: float) -> float:\n",
    "        \"\"\"P(X|Y) = P(X,Y) / P(Y)\"\"\"\n",
    "        prior = max(prior, self.config.epsilon)\n",
    "        return joint_probability / prior\n",
    "\n",
    "    def calculate_high_entropy_prior(self, entropy: float) -> float:\n",
    "        \"\"\"Prior adaptativo según entropía.\"\"\"\n",
    "        return 0.3 if entropy > self.config.high_entropy_threshold else 0.1\n",
    "\n",
    "    @validate_input_decorator(0.0, 1.0)\n",
    "    def calculate_high_coherence_prior(self, coherence: float) -> float:\n",
    "        \"\"\"Prior adaptativo según coherencia.\"\"\"\n",
    "        return 0.6 if coherence > self.config.high_coherence_threshold else 0.2\n",
    "\n",
    "    @validate_input_decorator(0.0, 1.0)\n",
    "    def calculate_joint_probability(self, coherence: float, action: int,\n",
    "                                   prn_influence: float) -> float:\n",
    "        \"\"\"Probabilidad conjunta basada en coherencia, acción e influencia PRN.\"\"\"\n",
    "        if coherence > self.config.high_coherence_threshold:\n",
    "            if action == 1:\n",
    "                return prn_influence * 0.8 + (1 - prn_influence) * 0.2\n",
    "            else:\n",
    "                return prn_influence * 0.1 + (1 - prn_influence) * 0.7\n",
    "        return 0.3\n",
    "\n",
    "    @timer_decorator\n",
    "    def calculate_probabilities_and_select_action(\n",
    "        self, entropy: float, coherence: float, prn_influence: float, action: int\n",
    "    ) -> Dict[str, float]:\n",
    "        \"\"\"Integra cálculos bayesianos para determinar acción.\"\"\"\n",
    "        # Normalizar si está fuera de rango\n",
    "        if entropy > 1.0:\n",
    "            entropy = 1.0 / (1.0 + np.exp(-entropy))\n",
    "        entropy = np.clip(entropy, 0.0, 1.0)\n",
    "\n",
    "        if coherence > 1.0:\n",
    "            coherence = 1.0 / (1.0 + np.exp(-coherence))\n",
    "        coherence = np.clip(coherence, 0.0, 1.0)\n",
    "\n",
    "        prn_influence = np.clip(prn_influence, 0.0, 1.0)\n",
    "\n",
    "        high_entropy_prior = self.calculate_high_entropy_prior(entropy)\n",
    "        high_coherence_prior = self.calculate_high_coherence_prior(coherence)\n",
    "\n",
    "        conditional_b_given_a = (\n",
    "            prn_influence * 0.7 + (1 - prn_influence) * 0.3\n",
    "            if entropy > self.config.high_entropy_threshold else 0.2\n",
    "        )\n",
    "\n",
    "        posterior_a_given_b = self.calculate_posterior_probability(\n",
    "            high_entropy_prior, high_coherence_prior, conditional_b_given_a\n",
    "        )\n",
    "\n",
    "        joint_probability_ab = self.calculate_joint_probability(\n",
    "            coherence, action, prn_influence\n",
    "        )\n",
    "\n",
    "        conditional_action_given_b = self.calculate_conditional_probability(\n",
    "            joint_probability_ab, high_coherence_prior\n",
    "        )\n",
    "\n",
    "        action_to_take = 1 if conditional_action_given_b > self.config.action_threshold else 0\n",
    "\n",
    "        return {\n",
    "            \"action_to_take\": action_to_take,\n",
    "            \"high_entropy_prior\": high_entropy_prior,\n",
    "            \"high_coherence_prior\": high_coherence_prior,\n",
    "            \"posterior_a_given_b\": posterior_a_given_b,\n",
    "            \"conditional_action_given_b\": conditional_action_given_b\n",
    "        }\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# INTEGRACIÓN CUÁNTICO-BAYESIANA\n",
    "# ============================================================================\n",
    "\n",
    "class QuantumBayesMahalanobis(BayesLogic):\n",
    "    \"\"\"Combina lógica bayesiana con Mahalanobis en estados cuánticos.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.covariance_estimator = EmpiricalCovariance()\n",
    "\n",
    "    def _get_inverse_covariance(self, data: np.ndarray) -> np.ndarray:\n",
    "        \"\"\"Retorna la inversa de la matriz de covarianza.\"\"\"\n",
    "        if data.ndim != 2:\n",
    "            raise ValueError(\"Los datos deben ser bidimensionales.\")\n",
    "        self.covariance_estimator.fit(data)\n",
    "        cov_matrix = self.covariance_estimator.covariance_\n",
    "        try:\n",
    "            inv_cov_matrix = np.linalg.inv(cov_matrix)\n",
    "        except np.linalg.LinAlgError:\n",
    "            inv_cov_matrix = np.linalg.pinv(cov_matrix)\n",
    "        return inv_cov_matrix\n",
    "\n",
    "    def compute_quantum_mahalanobis(self,\n",
    "                                    quantum_states_A: np.ndarray,\n",
    "                                    quantum_states_B: np.ndarray) -> np.ndarray:\n",
    "        \"\"\"Distancia de Mahalanobis vectorizada.\"\"\"\n",
    "        if quantum_states_A.ndim != 2 or quantum_states_B.ndim != 2:\n",
    "            raise ValueError(\"Los estados cuánticos deben ser matrices bidimensionales.\")\n",
    "        if quantum_states_A.shape[1] != quantum_states_B.shape[1]:\n",
    "            raise ValueError(\"Las dimensiones de A y B deben coincidir.\")\n",
    "\n",
    "        inv_cov_matrix = self._get_inverse_covariance(quantum_states_A)\n",
    "        mean_A = np.mean(quantum_states_A, axis=0)\n",
    "\n",
    "        diff_B = quantum_states_B - mean_A\n",
    "        aux = diff_B @ inv_cov_matrix\n",
    "        dist_sqr = np.einsum('ij,ij->i', aux, diff_B)\n",
    "        distances = np.sqrt(dist_sqr)\n",
    "        return distances\n",
    "\n",
    "    def quantum_cosine_projection(self,\n",
    "                                  quantum_states: np.ndarray,\n",
    "                                  entropy: float,\n",
    "                                  coherence: float,\n",
    "                                  n_step: int = 1) -> tf.Tensor:\n",
    "        \"\"\"Proyecta estados cuánticos con cosenos.\"\"\"\n",
    "        if quantum_states.shape[1] != 2:\n",
    "            raise ValueError(\"Se espera 'quantum_states' con 2 columnas.\")\n",
    "\n",
    "        cos_x, cos_y, cos_z = calculate_cosines(entropy, coherence)\n",
    "\n",
    "        projected_states_A = quantum_states * np.array([cos_x, cos_y])\n",
    "        projected_states_B = quantum_states * np.array([cos_x * cos_z, cos_y * cos_z])\n",
    "\n",
    "        mahalanobis_distances = self.compute_quantum_mahalanobis(\n",
    "            projected_states_A, projected_states_B\n",
    "        )\n",
    "\n",
    "        # Aplicar operador áureo\n",
    "        paridad, fase_mod = aureo_operator(n_step)\n",
    "        normalized_distances = np.tanh(mahalanobis_distances * paridad)\n",
    "\n",
    "        return tf.convert_to_tensor(normalized_distances, dtype=tf.float32)\n",
    "\n",
    "    def calculate_quantum_posterior_with_mahalanobis(self,\n",
    "                                                     quantum_states: np.ndarray,\n",
    "                                                     entropy: float,\n",
    "                                                     coherence: float):\n",
    "        \"\"\"Calcula posterior bayesiana en proyecciones cuánticas.\"\"\"\n",
    "        quantum_projections = self.quantum_cosine_projection(\n",
    "            quantum_states, entropy, coherence\n",
    "        )\n",
    "\n",
    "        tensor_projections = tf.convert_to_tensor(quantum_projections, dtype=tf.float32)\n",
    "        quantum_covariance = tfp.stats.covariance(tensor_projections, sample_axis=0)\n",
    "\n",
    "        dim = tf.cast(tf.shape(quantum_covariance)[0], tf.float32)\n",
    "        quantum_prior = tf.linalg.trace(quantum_covariance) / dim\n",
    "\n",
    "        prior_coherence = self.calculate_high_coherence_prior(coherence)\n",
    "        joint_prob = self.calculate_joint_probability(\n",
    "            coherence, 1, tf.reduce_mean(tensor_projections).numpy()\n",
    "        )\n",
    "        cond_prob = self.calculate_conditional_probability(joint_prob, quantum_prior.numpy())\n",
    "        posterior = self.calculate_posterior_probability(quantum_prior.numpy(),\n",
    "                                                         prior_coherence,\n",
    "                                                         cond_prob)\n",
    "        return posterior, quantum_projections\n",
    "\n",
    "    def predict_quantum_state(self,\n",
    "                              quantum_states: np.ndarray,\n",
    "                              entropy: float,\n",
    "                              coherence: float):\n",
    "        \"\"\"Predice el siguiente estado cuántico.\"\"\"\n",
    "        posterior, projections = self.calculate_quantum_posterior_with_mahalanobis(\n",
    "            quantum_states, entropy, coherence\n",
    "        )\n",
    "\n",
    "        next_state_prediction = tf.reduce_sum(\n",
    "            tf.multiply(\n",
    "                tf.cast(projections, tf.float32),\n",
    "                tf.cast(tf.expand_dims(posterior, -1), tf.float32) # Ensure both operands are tf.float32\n",
    "            ),\n",
    "            axis=0\n",
    "        )\n",
    "        return next_state_prediction, posterior\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# RUIDO PROBABILÍSTICO DE REFERENCIA (PRN)\n",
    "# ============================================================================\n",
    "\n",
    "class PRN:\n",
    "    \"\"\"Modelado del Ruido Probabilístico de Referencia.\"\"\"\n",
    "\n",
    "    def __init__(self, influence: float, algorithm_type: Optional[str] = None, **parameters):\n",
    "        if not 0 <= influence <= 1:\n",
    "            raise ValueError(f\"Influencia debe estar en [0,1]. Valor: {influence}\")\n",
    "        self.influence = influence\n",
    "        self.algorithm_type = algorithm_type\n",
    "        self.parameters = parameters\n",
    "\n",
    "    def adjust_influence(self, adjustment: float) -> None:\n",
    "        \"\"\"Ajusta influencia dentro de [0, 1].\"\"\"\n",
    "        new_influence = np.clip(self.influence + adjustment, 0, 1)\n",
    "        if new_influence != self.influence + adjustment:\n",
    "            print(f\"⚠️  Influencia ajustada a {new_influence}\")\n",
    "        self.influence = new_influence\n",
    "\n",
    "    def combine_with(self, other_prn: 'PRN', weight: float = 0.5) -> 'PRN':\n",
    "        \"\"\"Combina dos PRN según un peso.\"\"\"\n",
    "        if not 0 <= weight <= 1:\n",
    "            raise ValueError(f\"Peso debe estar en [0,1]. Valor: {weight}\")\n",
    "        combined_influence = self.influence * weight + other_prn.influence * (1 - weight)\n",
    "        combined_params = {**self.parameters, **other_prn.parameters}\n",
    "        algorithm = self.algorithm_type if weight >= 0.5 else other_prn.algorithm_type\n",
    "        return PRN(combined_influence, algorithm, **combined_params)\n",
    "\n",
    "    def __str__(self) -> str:\n",
    "        params_str = \", \".join(f\"{k}={v}\" for k, v in self.parameters.items())\n",
    "        algo_str = f\", algorithm={self.algorithm_type}\" if self.algorithm_type else \"\"\n",
    "        return f\"PRN(influence={self.influence:.4f}{algo_str}{', ' + params_str if params_str else ''})\"\n",
    "\n",
    "\n",
    "class EnhancedPRN(PRN):\n",
    "    \"\"\"Extiende PRN para registrar distancias de Mahalanobis.\"\"\"\n",
    "\n",
    "    def __init__(self, influence: float = 0.5, algorithm_type: str = None, **parameters):\n",
    "        super().__init__(influence, algorithm_type, **parameters)\n",
    "        self.mahalanobis_records = []\n",
    "\n",
    "    def record_quantum_noise(self, probabilities: dict, quantum_states: np.ndarray):\n",
    "        \"\"\"Registra ruido cuántico basado en Mahalanobis.\"\"\"\n",
    "        entropy = self.calculate_entropy_from_probabilities(probabilities)\n",
    "\n",
    "        cov_estimator = EmpiricalCovariance().fit(quantum_states)\n",
    "        mean_state = np.mean(quantum_states, axis=0)\n",
    "        inv_cov = np.linalg.pinv(cov_estimator.covariance_)\n",
    "\n",
    "        diff = quantum_states - mean_state\n",
    "        aux = diff @ inv_cov\n",
    "        dist_sqr = np.einsum('ij,ij->i', aux, diff)\n",
    "        distances = np.sqrt(dist_sqr)\n",
    "        mahal_mean = np.mean(distances)\n",
    "\n",
    "        self.mahalanobis_records.append(mahal_mean)\n",
    "        return entropy, mahal_mean\n",
    "\n",
    "    @staticmethod\n",
    "    def calculate_entropy_from_probabilities(probabilities: dict) -> float:\n",
    "        \"\"\"Calcula entropía de Shannon.\"\"\"\n",
    "        probs = np.array(list(probabilities.values()))\n",
    "        probs = probs[probs >= 0]\n",
    "        sum_probs = np.sum(probs)\n",
    "        if sum_probs > 0:\n",
    "            probs = probs / sum_probs\n",
    "        else:\n",
    "            probs = np.ones_like(probs) / len(probs)\n",
    "\n",
    "        probs = np.clip(probs, 1e-15, 1.0)\n",
    "        return -np.sum(probs * np.log2(probs))\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# COLAPSO DE ONDA CON ESTRUCTURA METRIPLÉCTICA\n",
    "# ============================================================================\n",
    "\n",
    "class QuantumNoiseCollapse(QuantumBayesMahalanobis):\n",
    "    \"\"\"Simula colapso de onda cuántico con estructura metripléctica.\"\"\"\n",
    "\n",
    "    def __init__(self, prn_influence: float = 0.5):\n",
    "        super().__init__()\n",
    "        self.prn = EnhancedPRN(influence=prn_influence)\n",
    "        self.aureo_n_step = 1\n",
    "\n",
    "    @timer_decorator\n",
    "    def simulate_wave_collapse_metriplectic(self,\n",
    "                                            quantum_states: np.ndarray,\n",
    "                                            density_matrix: np.ndarray,\n",
    "                                            prn_influence: float,\n",
    "                                            previous_action: int,\n",
    "                                            M: Optional[np.ndarray] = None):\n",
    "        \"\"\"Simula colapso de onda con estructura metripléctica.\"\"\"\n",
    "        if M is None:\n",
    "            M = np.eye(2) * 0.1\n",
    "\n",
    "        # 1. Entropía von Neumann\n",
    "        von_neumann_ent = VonNeumannEntropy.compute_von_neumann_entropy(\n",
    "            density_matrix, normalize=True, method=\"sigmoid\"\n",
    "        )\n",
    "\n",
    "        # 2. Ruido cuántico\n",
    "        magnitudes = np.array([np.linalg.norm(state) for state in quantum_states])\n",
    "        sum_magnitudes = np.sum(magnitudes)\n",
    "        if sum_magnitudes > 0:\n",
    "            normalized_magnitudes = magnitudes / sum_magnitudes\n",
    "        else:\n",
    "            normalized_magnitudes = np.ones_like(magnitudes) / len(magnitudes)\n",
    "\n",
    "        probabilities = {str(i): p for i, p in enumerate(normalized_magnitudes)}\n",
    "        entropy, mahalanobis_mean = self.prn.record_quantum_noise(probabilities, quantum_states)\n",
    "\n",
    "        # Normalizar entropía\n",
    "        entropy_normalized = 1.0 / (1.0 + np.exp(-entropy)) if entropy > 1.0 else entropy\n",
    "        entropy_normalized = np.clip(entropy_normalized, 0.0, 1.0)\n",
    "\n",
    "        mahalanobis_normalized = 1.0 / (1.0 + np.exp(-mahalanobis_mean))\n",
    "        mahalanobis_normalized = np.clip(mahalanobis_normalized, 0.0, 1.0)\n",
    "\n",
    "        # 3. Cosenos directores\n",
    "        cos_x, cos_y, cos_z = calculate_cosines(entropy_normalized, mahalanobis_normalized)\n",
    "\n",
    "        # 4. Coherencia\n",
    "        coherence = np.exp(-mahalanobis_normalized) * (cos_x + cos_y + cos_z) / 3.0\n",
    "\n",
    "        # 5. Lógica bayesiana\n",
    "        bayes_probs = self.calculate_probabilities_and_select_action(\n",
    "            entropy=entropy_normalized,\n",
    "            coherence=coherence,\n",
    "            prn_influence=prn_influence,\n",
    "            action=previous_action\n",
    "        )\n",
    "\n",
    "        # 6. Proyección cuántica\n",
    "        projected_states = self.quantum_cosine_projection(\n",
    "            quantum_states, entropy_normalized, coherence, n_step=self.aureo_n_step\n",
    "        )\n",
    "\n",
    "        # 7. Evolución metripléctica\n",
    "        q_val = np.array([entropy_normalized])\n",
    "        p_val = np.array([coherence])\n",
    "\n",
    "        metriplectic_evolution = MetriplecticStructure.metriplectic_evolution(\n",
    "            H, S, H, q_val, p_val, M\n",
    "        )\n",
    "\n",
    "        # 8. Colapso final\n",
    "        collapsed_state = tf.reduce_sum(\n",
    "            tf.multiply(\n",
    "                projected_states,\n",
    "                tf.cast(bayes_probs[\"action_to_take\"], tf.float32) * self.aureo_n_step\n",
    "            )\n",
    "        )\n",
    "\n",
    "        self.aureo_n_step += 1\n",
    "\n",
    "        return {\n",
    "            \"collapsed_state\": collapsed_state.numpy(),\n",
    "            \"action\": bayes_probs[\"action_to_take\"],\n",
    "            \"shannon_entropy\": entropy,\n",
    "            \"shannon_entropy_normalized\": entropy_normalized,\n",
    "            \"von_neumann_entropy\": von_neumann_ent,\n",
    "            \"coherence\": coherence,\n",
    "            \"mahalanobis_distance\": mahalanobis_mean,\n",
    "            \"mahalanobis_normalized\": mahalanobis_normalized,\n",
    "            \"cosines\": (cos_x, cos_y, cos_z),\n",
    "            \"metriplectic_evolution\": metriplectic_evolution,\n",
    "            \"bayesian_posterior\": bayes_probs[\"posterior_a_given_b\"]\n",
    "        }\n",
    "\n",
    "    @timer_decorator\n",
    "    def objective_function_with_noise(self,\n",
    "                                      quantum_states: tf.Tensor,\n",
    "                                      target_state: np.ndarray,\n",
    "                                      entropy_weight: float = 1.0,\n",
    "                                      n_step: int = 1) -> tf.Tensor:\n",
    "        \"\"\"Función objetivo con ruido (estabilizada).\"\"\"\n",
    "        paridad, fase_mod = aureo_operator(n_step)\n",
    "        target_modulado = tf.cast(target_state, tf.float32) * tf.cast(fase_mod, tf.float32)\n",
    "\n",
    "        fidelity = tf.abs(tf.reduce_sum(quantum_states * target_modulado))**2\n",
    "\n",
    "        quantum_states_np = quantum_states.numpy()\n",
    "        magnitudes = np.array([np.linalg.norm(state) for state in quantum_states_np])\n",
    "        sum_magnitudes = np.sum(magnitudes)\n",
    "        if sum_magnitudes > 0:\n",
    "            normalized_magnitudes = magnitudes / sum_magnitudes\n",
    "        else:\n",
    "            normalized_magnitudes = np.ones_like(magnitudes) / len(magnitudes)\n",
    "\n",
    "        probabilities_for_shannon = {str(i): p for i, p in enumerate(normalized_magnitudes)}\n",
    "        entropy, mahalanobis_dist = self.prn.record_quantum_noise(probabilities_for_shannon, quantum_states_np)\n",
    "\n",
    "        mahalanobis_dist_clipped = np.clip(mahalanobis_dist, 0, 1000.0)\n",
    "        mahalanobis_term = tf.stop_gradient(1.0 - tf.exp(-tf.cast(mahalanobis_dist_clipped, tf.float32)))\n",
    "\n",
    "        paridad_tf = tf.cast(paridad, tf.float32)\n",
    "        entropy_clipped_tf = tf.cast(np.clip(entropy, 0, 1000.0), tf.float32)\n",
    "        entropy_weight_tf = tf.cast(entropy_weight, tf.float32)\n",
    "\n",
    "        paridad_term = tf.abs(tf.reduce_mean(quantum_states) - paridad_tf)\n",
    "\n",
    "        objective_value = (\n",
    "            (1.0 - fidelity)\n",
    "            + entropy_weight_tf * entropy_clipped_tf\n",
    "            + mahalanobis_term\n",
    "            + 0.5 * paridad_term\n",
    "        )\n",
    "\n",
    "        return objective_value\n",
    "\n",
    "    @timer_decorator\n",
    "    def optimize_quantum_state(self,\n",
    "                               initial_states: np.ndarray,\n",
    "                               target_state: np.ndarray,\n",
    "                               max_iterations: int = 100,\n",
    "                               learning_rate: float = 0.01):\n",
    "        \"\"\"Optimiza estados cuánticos mediante descenso de gradiente (Adam).\"\"\"\n",
    "        current_states = tf.Variable(initial_states.astype(np.float32), dtype=tf.float32)\n",
    "\n",
    "        best_objective = float('inf')\n",
    "        best_states = current_states.numpy().copy()\n",
    "\n",
    "        optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)\n",
    "\n",
    "        for i in range(1, max_iterations + 1):\n",
    "            with tf.GradientTape() as tape:\n",
    "                objective = self.objective_function_with_noise(current_states, target_state, n_step=i)\n",
    "\n",
    "            grads = tape.gradient(objective, [current_states])\n",
    "\n",
    "            if grads[0] is None or tf.reduce_any(tf.math.is_nan(grads[0])):\n",
    "                print(f\"⚠️  Deteniendo en iteración {i} por gradiente inválido\")\n",
    "                break\n",
    "\n",
    "            optimizer.apply_gradients(zip(grads, [current_states]))\n",
    "\n",
    "            new_objective = self.objective_function_with_noise(current_states, target_state, n_step=i)\n",
    "            if new_objective < best_objective:\n",
    "                best_objective = new_objective\n",
    "                best_states = current_states.numpy().copy()\n",
    "\n",
    "        return best_states, float(best_objective)\n",
    "\n",
    "\n",
    "# ============================================================================\n",
    "# EJEMPLO DE USO INTEGRADO\n",
    "# ============================================================================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"=\" * 80)\n",
    "    print(\"⚛️  QuoreMind v1.0.0: Sistema Metripléctico Cuántico-Bayesiano\")\n",
    "    print(\"=\" * 80)\n",
    "\n",
    "    # 1. Crear matriz de densidad\n",
    "    state = np.array([1/np.sqrt(2), 1/np.sqrt(2)])\n",
    "    density_matrix = VonNeumannEntropy.density_matrix_from_state(state)\n",
    "\n",
    "    # 2. Estados cuánticos\n",
    "    np.random.seed(42)\n",
    "    quantum_states = np.random.randn(10, 2)\n",
    "\n",
    "    # 3. Crear sistema\n",
    "    collapse_system = QuantumNoiseCollapse(prn_influence=0.6)\n",
    "\n",
    "    # 4. Matriz métrica\n",
    "    M = np.array([[0.1, 0.0], [0.0, 0.1]])\n",
    "\n",
    "    # ========================================================================\n",
    "    # PARTE 1: SIMULACIÓN DE COLAPSO METRIPLÉCTICO\n",
    "    # ========================================================================\n",
    "    print(\"\\n📊 1. ANÁLISIS CON ESTRUCTURA METRIPLÉCTICA (Ciclo 1)\")\n",
    "    print(\"-\" * 80)\n",
    "\n",
    "    collapse_result = collapse_system.simulate_wave_collapse_metriplectic(\n",
    "        quantum_states=quantum_states,\n",
    "        density_matrix=density_matrix,\n",
    "        prn_influence=0.6,\n",
    "        previous_action=1,\n",
    "        M=M\n",
    "    )\n",
    "\n",
    "    print(f\"✓ Estado colapsado: {collapse_result['collapsed_state']:.6f}\")\n",
    "    print(f\"✓ Acción tomada: {collapse_result['action']}\")\n",
    "    print(f\"✓ Entropía Shannon (norm): {collapse_result['shannon_entropy_normalized']:.6f}\")\n",
    "    print(f\"✓ Entropía von Neumann: {collapse_result['von_neumann_entropy']:.6f}\")\n",
    "    print(f\"✓ Coherencia: {collapse_result['coherence']:.6f}\")\n",
    "    print(f\"✓ Mahalanobis (norm): {collapse_result['mahalanobis_normalized']:.6f}\")\n",
    "    print(f\"✓ Evolución metripléctica: {collapse_result['metriplectic_evolution']:.6f}\")\n",
    "    print(f\"✓ Posterior bayesiana: {collapse_result['bayesian_posterior']:.6f}\")\n",
    "    cos_x, cos_y, cos_z = collapse_result['cosines']\n",
    "    print(f\"✓ Cosenos (x, y, z): ({cos_x:.4f}, {cos_y:.4f}, {cos_z:.4f})\")\n",
    "\n",
    "    # ========================================================================\n",
    "    # PARTE 2: CORCHETES DE POISSON\n",
    "    # ========================================================================\n",
    "    print(\"\\n🔄 2. ANÁLISIS DE CORCHETES DE POISSON\")\n",
    "    print(\"-\" * 80)\n",
    "\n",
    "    entropy_val = collapse_result['shannon_entropy_normalized']\n",
    "    coherence_val = collapse_result['coherence']\n",
    "\n",
    "    x_obs = lambda q, p: q\n",
    "    p_obs = lambda q, p: p\n",
    "\n",
    "    q_test = np.array([entropy_val])\n",
    "    p_test = np.array([coherence_val])\n",
    "\n",
    "    pb_xh = PoissonBrackets.poisson_bracket(x_obs, H, q_test, p_test)\n",
    "    pb_ph = PoissonBrackets.poisson_bracket(p_obs, H, q_test, p_test)\n",
    "\n",
    "    print(f\"✓ {{x, H}}: {pb_xh:.6f} (esperado: p ≈ {coherence_val:.6f})\")\n",
    "    print(f\"✓ {{p, H}}: {pb_ph:.6f} (esperado: -q ≈ {-entropy_val:.6f})\")\n",
    "\n",
    "    df_dt = PoissonBrackets.liouville_evolution(H, x_obs, q_test, p_test)\n",
    "    print(f\"✓ dx/dt = {{x, H}}: {df_dt:.6f}\")\n",
    "\n",
    "    # ========================================================================\n",
    "    # PARTE 3: ESTRUCTURA METRIPLÉCTICA EN DETALLE\n",
    "    # ========================================================================\n",
    "    print(\"\\n⚙️  3. ESTRUCTURA METRIPLÉCTICA DETALLADA\")\n",
    "    print(\"-\" * 80)\n",
    "\n",
    "    metrib_hs = MetriplecticStructure.metriplectic_bracket(H, S, q_test, p_test, M)\n",
    "    print(f\"✓ [H, S]_M (metriplexico): {metrib_hs:.6f}\")\n",
    "\n",
    "    dh_dt = MetriplecticStructure.metriplectic_evolution(H, S, H, q_test, p_test, M)\n",
    "    print(f\"✓ dH/dt (reversible+disipativa): {dh_dt:.6f}\")\n",
    "\n",
    "    ds_dt = MetriplecticStructure.metriplectic_evolution(H, S, S, q_test, p_test, M)\n",
    "    print(f\"✓ dS/dt (producción de entropía): {ds_dt:.6f}\")\n",
    "\n",
    "    # ========================================================================\n",
    "    # PARTE 4: OPTIMIZACIÓN\n",
    "    # ========================================================================\n",
    "    print(\"\\n📈 4. OPTIMIZACIÓN DE ESTADOS CUÁNTICOS\")\n",
    "    print(\"-\" * 80)\n",
    "\n",
    "    target_state = np.array([0.8, 0.2])\n",
    "    initial_states = np.random.randn(5, 2)\n",
    "\n",
    "    optimized_states, final_objective = collapse_system.optimize_quantum_state(\n",
    "        initial_states=initial_states,\n",
    "        target_state=target_state,\n",
    "        max_iterations=50,\n",
    "        learning_rate=0.01\n",
    "    )\n",
    "\n",
    "    initial_objective = collapse_system.objective_function_with_noise(\n",
    "        tf.convert_to_tensor(initial_states.astype(np.float32)),\n",
    "        target_state,\n",
    "        n_step=1\n",
    "    )\n",
    "\n",
    "    print(f\"✓ Objetivo inicial: {initial_objective:.6f}\")\n",
    "    print(f\"✓ Objetivo final: {final_objective:.6f}\")\n",
    "    print(f\"✓ Mejora: {initial_objective - final_objective:.6f}\")\n",
    "\n",
    "    # ========================================================================\n",
    "    # PARTE 5: EVOLUCIÓN TEMPORAL\n",
    "    # ========================================================================\n",
    "    print(\"\\n🔁 5. EVOLUCIÓN TEMPORAL DEL SISTEMA\")\n",
    "    print(\"-\" * 80)\n",
    "\n",
    "    print(\"Simulando 5 ciclos de colapso:\")\n",
    "    current_states = quantum_states.copy()\n",
    "\n",
    "    for cycle in range(5):\n",
    "        result = collapse_system.simulate_wave_collapse_metriplectic(\n",
    "            quantum_states=current_states,\n",
    "            density_matrix=density_matrix,\n",
    "            prn_influence=0.6,\n",
    "            previous_action=1 if cycle % 2 == 0 else 0,\n",
    "            M=M\n",
    "        )\n",
    "\n",
    "        print(f\"\\n  Ciclo {cycle + 1}:\")\n",
    "        print(f\"    - von Neumann entropy: {result['von_neumann_entropy']:.4f}\")\n",
    "        print(f\"    - Shannon (norm): {result['shannon_entropy_normalized']:.4f}\")\n",
    "        print(f\"    - Mahalanobis (norm): {result['mahalanobis_normalized']:.4f}\")\n",
    "        print(f\"    - Evolución metripléctica: {result['metriplectic_evolution']:.4f}\")\n",
    "        print(f\"    - Acción: {result['action']}\")\n",
    "\n",
    "        current_states = current_states + np.random.randn(*current_states.shape) * 0.01\n",
    "\n",
    "    # ========================================================================\n",
    "    # PARTE 6: ANÁLISIS CON OPERADOR ÁUREO Y λ_DOBLE\n",
    "    # ========================================================================\n",
    "    print(\"\\n\" + \"=\" * 80)\n",
    "    print(\"🔷 6. ANÁLISIS CON OPERADOR ÁUREO Y PARÁMETRO λ_DOBLE\")\n",
    "    print(\"=\" * 80)\n",
    "\n",
    "    # Estados indexados\n",
    "    initial_states_indexed = np.array([\n",
    "        [0.1 * i, 0.1 * (i + 1)] for i in range(10)\n",
    "    ], dtype=np.float32)\n",
    "\n",
    "    print(\"\\n📌 Estados iniciales indexados:\")\n",
    "    print(initial_states_indexed)\n",
    "\n",
    "    # Hamiltoniano\n",
    "    H_local = lambda q, p: 0.5 * p**2 + 0.5 * q**2\n",
    "    qubits = np.linspace(0.1, 1.0, 10)\n",
    "\n",
    "    print(f\"\\n📊 Qubits: {qubits}\")\n",
    "\n",
    "    # Calcular λ_doble para estados legítimos\n",
    "    print(\"\\n🟢 Parámetro λ_doble (Estados Legítimos):\")\n",
    "    lambda_legit = []\n",
    "    for i, state in enumerate(initial_states_indexed):\n",
    "        lam = lambda_doble_operator(state, H_local, qubits, golden_phase=0)\n",
    "        lambda_legit.append(lam)\n",
    "        if i < 3:\n",
    "            print(f\"   Estado {i}: λ_doble = {lam:.6f}\")\n",
    "    print(f\"   ... (10 total)\")\n",
    "\n",
    "    mean_legit = np.mean(lambda_legit)\n",
    "    std_legit = np.std(lambda_legit)\n",
    "    print(f\"\\n   Media: {mean_legit:.6f}\")\n",
    "    print(f\"   Desv. Est.: {std_legit:.6f}\")\n",
    "\n",
    "    # Estados anómalos\n",
    "    print(\"\\n🔴 Generando Estados Anómalos:\")\n",
    "    anomalous_states = np.random.randn(5, 2) * 5.0 + np.array([2.0, 2.0])\n",
    "\n",
    "    lambda_anomaly = []\n",
    "    for i, state in enumerate(anomalous_states):\n",
    "        lam = lambda_doble_operator(state, H_local, qubits, golden_phase=1)\n",
    "        lambda_anomaly.append(lam)\n",
    "        print(f\"   Estado {i}: λ_doble = {lam:.6f}\")\n",
    "\n",
    "    threshold = mean_legit + 3 * std_legit\n",
    "    print(f\"\\n⚠️  Umbral de detección (3σ): {threshold:.6f}\")\n",
    "\n",
    "    anomalies_detected = [lam > threshold for lam in lambda_anomaly]\n",
    "    detected_count = sum(anomalies_detected)\n",
    "    print(f\"\\n✓ Anomalías detectadas: {detected_count}/{len(anomalous_states)}\")\n",
    "\n",
    "    # ========================================================================\n",
    "    # RESUMEN FINAL\n",
    "    # ========================================================================\n",
    "    print(\"\\n\" + \"=\" * 80)\n",
    "    print(\"📊 RESUMEN FINAL\")\n",
    "    print(\"=\" * 80)\n",
    "\n",
    "    print(f\"\"\"\n",
    "✓ Operador Áureo (φ-operator):\n",
    "  - 10 estados indexados procesados\n",
    "  - Modulación de fase cuasiperiódica integrada\n",
    "  - Estabilización de optimización: ACTIVA\n",
    "\n",
    "✓ Parámetro λ_doble (λ₂):\n",
    "  - Detecta anomalías mediante:\n",
    "    * Amplitud máxima de estado\n",
    "    * Operador áureo (φ)\n",
    "    * Efectos Hamiltonianos\n",
    "    * Media de qubits\n",
    "  - Umbral de detección: {threshold:.6f}\n",
    "  - Sensibilidad: {(detected_count/len(anomalous_states))*100:.1f}%\n",
    "\n",
    "✓ Estructura Metripléctica:\n",
    "  - Parte reversible (Poisson): {pb_xh:.6f}\n",
    "  - Parte disipativa (Métrica): {metrib_hs:.6f}\n",
    "  - Producción de entropía: {ds_dt:.6f}\n",
    "\n",
    "✓ Lógica Bayesiana:\n",
    "  - Posterior: {collapse_result['bayesian_posterior']:.6f}\n",
    "  - Coherencia: {collapse_result['coherence']:.6f}\n",
    "  - Acción: {'ACEPTAR' if collapse_result['action'] else 'BLOQUEAR'}\n",
    "\n",
    "✓ Optimización:\n",
    "  - Mejora de pérdida: {initial_objective - final_objective:.6f}\n",
    "  - Iteraciones: 50\n",
    "  - Convergencia: ✓ EXITOSA\n",
    "    \"\"\")\n",
    "\n",
    "    print(\"=\" * 80)\n",
    "    print(\"✅ QuoreMind v1.0.0 - Análisis Completo\")\n",
    "    print(\"=\" * 80)"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "isSourceIdPinned": true,
     "modelId": 389729,
     "modelInstanceId": 368850,
     "sourceId": 454696,
     "sourceType": "modelInstanceVersion"
    }
   ],
   "dockerImageVersionId": 31259,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 33.438863,
   "end_time": "2026-02-12T18:27:09.672995",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-02-12T18:26:36.234132",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
